[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"
