name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # Remove remote if already exists
          git remote remove hf || true
          
          # Adiciona o repositório do HF com autenticação via token
          git remote add hf https://medjotavesf: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$@huggingface.co/spaces/medjotavesf/Nexus-QuantumI2A2

          # Garante envio completo, criando branch main se necessário
          git push hf HEAD:main --force
